name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da imagem Docker
        run: docker build -t ci-cd-app .

      - name: Teste fake
        run: echo "Testes executados com sucesso!"

      - name: Deploy simulado
        run: echo "Deploy realizado com sucesso!"
